[Feat] VC API 활용 result 생성
FC-DEV-FinalProject/FinalProject_5RE5_BE pull request #136
Opened 2024-11-18 11:02 UTC by alswooy

- VC API 활용 서비스단 생성
- VC 컨트롤러 적용

2024-11-18 14:07 UTC, oowtl requested changes

2024-11-18 14:07 UTC, oowtl commented on src/test/java/com/oreo/finalproject_5re5_be/vc/service/VcApiServiceImplTest.java
> +//    @DisabledOnOs({OS.LINUX})
삭제 인가요..?

2024-11-19 02:51 UTC, oowtl approved these changes

2024-11-19 05:13 UTC, jongheonleee approved these changes
Good!

2024-11-19 05:14 UTC, merged