[feat] 회원가입 기능 개발 구현
FC-DEV-FinalProject/FinalProject_5RE5_BE pull request #35
Opened 2024-11-10 13:13 UTC by jongheonleee

## 작업 내용
- 회원가입 기능 구현
- 회원 필드 유효성 검증
- 회원 가입시 발생되는 서버에러 복구 작업 처리
- 그 외의 비즈니스 로직 및 예외 정의
- 구현 및 테스트 완료 

## 기타:
> 참고 내용:

- 현재 스프링 시큐리티 적용하려고 함. 다른 파트에서 API 호출을 할 경우 403 에러 발생할 경우가 높음. 이 부분 API 명세서 참고하면서 적용할 계획임

2024-11-10 13:29 UTC, jongheonleee commented
현제 로컬에선 테스트가 정상적으로 통과하지만 깃허브 액션에서는 걸러지네요. 흐음. 혹시 제가 놓친 설정이 있을까여?

2024-11-10 13:38 UTC, oowtl commented
@TestPropertySource(locations = "classpath:application-test.properties") 
다른 테스트에도 이거 달아주세용

2024-11-10 13:48 UTC, jongheonleee commented
방금 수정했습니다. 깃허브 액션도 정상적으로 돌아가네요!

2024-11-10 13:55 UTC, K-KY commented on src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberRegisterRequest.java
> +
### 제3조 (개인정보 보호 원칙) ① 개인정보처리자는 개인정보의 처리 목적을 명확하게 하여야 하고 그 목적에 필요한 범위에서 최소한의 개인정보만을 적법하고 정당하게 수집하여야 한다.

### 제16조 (개인정보의 수집 제한) ① 개인정보처리자는 제15조 제1항 각 호의 어느 하나에 해당하여 개인정보를 수집하는 경우에는 그 목적에 필요한 최소한의 개인정보를 수집하여야 한다.

사용자 정보 수집에는 법적인 제약조건이 있습니다. 
어플리케이션 이용에 필요한 정보가 아니라면 수집하지 않는것이 좋을것 같습니다

2024-11-10 13:55 UTC, K-KY commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/Member.java
> +    @Column(name = "member_seq")
ERD에 정의 되어있는 내용으로 작업을 하기 때문에 다른 분들은 이미 연동된 엔티티를  `user...` 로 하신 상태입니다.
공유 없이 테이블의 이름을 바꾸면 혼란이 생길 수 있습니다!

2024-11-10 14:28 UTC, jongheonleee commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/Member.java
> +    @Column(name = "member_seq")
현재 user라는 이름이 DB에서 예약어로 활용되고 있어서 테이블명과 예약어 명이 동일하여 발생되는 에러가 있습니다. 그 부분 때문에 이름 변경했습니다. 자세한 내용은 월요일날 얘기하겠습니다

2024-11-10 14:30 UTC, jongheonleee commented on src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberRegisterRequest.java
> +
넵. 해당 부분은 이미 프론트 측이랑 데이터 입력 값 정해 놓은 상황입니다. 일단 이렇게 진행하겠습니다

2024-11-10 14:42 UTC, K-KY commented on src/main/java/com/oreo/finalproject_5re5_be/member/service/MemberServiceImpl.java
> +    )
실패시 재시도 하는 로직을 어렵게 구현한 적이 있었는데 이렇게 하는 방법이 있었네요. 좋은거 배워갑니다.

2024-11-10 14:44 UTC, K-KY approved these changes

2024-11-10 14:54 UTC, jongheonleee commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberTermsHistory.java
> +    }
넵 한번 찾아 보겠습니다~

2024-11-11 02:07 UTC, oowtl requested changes

2024-11-11 02:07 UTC, oowtl commented on src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
> +    public ResponseEntity<MemberRegisterResponse> register(@Valid @RequestBody MemberRegisterRequest memberRegisterRequest, BindingResult result) {
controller 내용에 대한 주석 부탁드려용

2024-11-11 02:07 UTC, oowtl commented on src/main/java/com/oreo/finalproject_5re5_be/member/dto/request/MemberRegisterRequest.java
> +    public MemberTermsHistory createMemberTermsHistoryEntity(Member member) {
메서드 내용에 대한 주석 부탁드릴게용

2024-11-11 02:07 UTC, oowtl commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/Member.java
> +@AllArgsConstructor
@AllArgsConstructor 를 public 으로 두신 이유가 있을까요? @AllArgsConstructor 를 private 로 만들고 @NoArgsConstructor 를 protected 로 해도 JPA가 동작해서용

2024-11-11 02:07 UTC, oowtl commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberTermsHistory.java
> +    public void addMemberTermCondition(int i, Character chk) {
스위치문은 사용하지 않기로 한 것 같은데요.. 혹시 사용하신 이유가 있을까요?

2024-11-11 02:17 UTC, jongheonleee commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberTermsHistory.java
> +    public void addMemberTermCondition(int i, Character chk) {
해당 부분은 for문으로 작성하면 for문이랑 if문 같이 사용하게 되어 코드가 비효율적인 것 같아서 switch문 사용했습니다.

2024-11-11 02:18 UTC, jongheonleee commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/Member.java
> +@AllArgsConstructor
별다른 이유 없이 사용했습니다.
현재 1차 개발 빠르게 구현하는 것에 초점을 두고 있어서 빠르게 구현하고 리팩토링 단계에서 처리하겠습니다!

2024-11-11 02:19 UTC, jongheonleee commented on src/main/java/com/oreo/finalproject_5re5_be/member/controller/MemberController.java
> +    public ResponseEntity<MemberRegisterResponse> register(@Valid @RequestBody MemberRegisterRequest memberRegisterRequest, BindingResult result) {
네엡~

2024-11-11 03:00 UTC, oowtl commented on src/main/java/com/oreo/finalproject_5re5_be/member/entity/MemberTermsHistory.java
> +    public void addMemberTermCondition(int i, Character chk) {
음... if 문으로도 할 수 있지 않을까요..?

2024-11-11 03:24 UTC, oowtl approved these changes
감사합니다!

2024-11-11 03:26 UTC, merged